### ISSUE TITLE
How to run the code? will you provide the checkpoint soon? 

### ISSUE THREAD

**Issue by lezhang7** [liyongqi67/MMCoQA#3]
as title

**Comment by shihabrashid-ucr** [comment]
Were you able to run the code and reproduce the results from their paper?

**Comment by liyongqi67** [comment]
I just updated the running steps. In case of any other queries, please do not hesitate to email me directly as I do not frequently check GitHub issues.

**Comment by liyongqi67** [comment]
Reopen this issue if have other problems
