### ISSUE TITLE
Unable to reproduce the results published in the paper!

### ISSUE THREAD

**Issue by shihabrashid-ucr** [liyongqi67/MMCoQA#5]
Hi, I was able to run your code and the results generated are vastly different (worse) from what was published in the paper (ACL 2022). There are not any instructions to run your code but I assume I need to first run `train_retriever.py` to pretrain the retriever and then run `train_pipeline.py`. There are many parameters to choose and the values were not provided in the README but I chose some of the values based on the paper and left other parameters to their default values.

I am testing it in a Ubuntu system with 1 GPU Tesla V100.
Here are the steps I followed. In `train_retriever.py` the parameters I changed, all others I kept default:
```
--train_file, --dev_file, --test_file, --qrels, --passages_file, --tables_file, --images_file : (path to the data files)
--output_dir: ./retriever_release_full
--given_query: True
--given_passage: True
--is_pretraining: True
--only_positive_passage: True
--gen_passage_rep_output: './retriever_release_full/dev_blocks.txt'
--do_train: True
--do_eval: True
--do_test: False
--per_gpu_train_batch_size: 7 (I tried it with 4 too as mentioned in paper but it produced worse results)
--per_gpu_eval_batch_size: 128
--learning_rate: 0.0001 (as mentioned in paper)
--num_train_epochs: 12.0
--eval_all_checkpoints: True
--seed: 42
--history_num: 1
```
After this code runs, it creates a `dev_blocks.txt` which is the passage rep of all documents in the collection (and it was created with checkpoint 7861). This is the result of the `predictions` file in `./retriever_release_full/predictions/all_results.json`:
```
{"NDCG_2000": 0.01547891817940833, "Recall_2000": 0.12048192771084337, 
"NDCG_4000": 0.021736332376964273, "Recall_4000": 0.16179001721170397, 
"NDCG_6000": 0.030545229155134152, "Recall_6000": 0.22375215146299485, 
"NDCG_7861": 0.04768772313908916, "Recall_7861": 0.3373493975903614}
```
Here the results seem very low (I think the values are 100 multiplied already) but I choose the best metric which is `7861`.
Then I run `train_pipeline.py` with these parameters (I am mentioning only those that I changed, the other values are default):
```
--gen_passage_rep_output: './retriever_release_full/dev_blocks.txt'
--output_dir: './release_full'
--history_num: 6 (in the paper it was mentioned a sliding window and Chen et.al. paper was mentioned, they used history_num=6, default value was 1)
--do_train, --do_eval, --do_test : True
--per_gpu_train_batch_size: 1 (as from paper)
--per_gpu_eval_batch_size: 1
--learning_rate: 0.0001 (as from paper)
--retrieve_checkpoint: './retriever_release_full/checkpoint-7861'
--retreive_tokenizer_dir: './retriever_release_full'
--top_k_for_retriever: 2000
--top_k_for_reader: 6 (default was 5, In paper it was mentioned 10 but I was getting CUDA error with >6, I tried it with default value 5 but worse results)
```
This generated final results for the dev set and test set. These are all the results on dev set for all checkpoints, `./release_full/predictions/all_results.json`
```
{"f1_12000": 0.1999550545799847, "human_f1_12000": 87.51094172608802, "EM_12000": 0.0, 
"retriever_ndcg_12000": 0.10854495792415325, "retriever_recall_12000": 1.0, 
"f1_13747": 18.171749561332195, "human_f1_13747": 87.51094172608802, "EM_13747": 0.11359724612736662, "retriever_ndcg_13747": 0.10753786719233988, "retriever_recall_13747": 1.0, 
"f1_4000": 0.1981156758596689, "human_f1_4000": 87.51094172608802, "EM_4000": 0.0, 
"retriever_ndcg_4000": 0.1082621002238686, "retriever_recall_4000": 1.0, 
"f1_8000": 14.206993203515648, "human_f1_8000": 87.51094172608802, "EM_8000": 0.08777969018932874, 
"retriever_ndcg_8000": 0.10866859315542725, "retriever_recall_8000": 1.0}
```

The results are very confusing, first, all retriever recall is 1.0, upon checking manually from `./release_full/predictions/instance_predictions_13747`, it seems that, regardless of the question, for every conversation the top 6 passages returned are the same! hence recall is 1.0, and as the passages are images, the answers vary very much which is nowhere related to the original answer. But somehow the f1 score is very high. NDCG score is nowhere related to the dev set results mentioned in the paper.

These are the test set results: `./release_full/predictions/metrics_test`:
```
{"f1": 20.493238492579152, "human_f1": 93.24725462861055, "EM": 0.13220338983050847, 
"retriever_ndcg": 0.10925932368782416, "retriever_recall": 1.0}
```
Here is a sample example from `./release_full/predictions/instance_predictions_test.json` using checkpoint-13747:
```
"C_226_0": [
        {
            "text": "Seijun Suzuki Daniil Kulikov",
            "start_logit": -2.446899890899658,
            "end_logit": -1.6561766862869263,
            "retrieval_logit": 0.704164981842041,
            "retriever_prob": 0.16670076549053192,
            "example_id": "C_226_0*ecf05f655a5e6839c4b5b618e0aafd93"
        },
        {
            "text": "Uncredited 1949 Madness of the Heart Nun 1952 Wings of Danger Nurse Uncredited 1954 Lease of Life Mistress of Ceremonies 1955 Value for Money",
            "start_logit": -6.878751277923584,
            "end_logit": -7.3055291175842285,
            "retrieval_logit": -10.26059627532959,
            "retriever_prob": 0.16670021414756775,
            "example_id": "C_226_0*9a32668ca7c067b123ac647e4031f399"
        },
        {
            "text": "Richard Fenwick",
            "start_logit": -5.242187976837158,
            "end_logit": -2.569617986679077,
            "retrieval_logit": -6.643885135650635,
            "retriever_prob": 0.16667866706848145,
            "example_id": "C_226_0*5741b10b6f1137fc49045217a721a2d0"
        },
        {
            "text": "Brian Wilde Mr Barrowclough",
            "start_logit": -5.662569522857666,
            "end_logit": -6.307912349700928,
            "retrieval_logit": -9.987076759338379,
            "retriever_prob": 0.16667206585407257,
            "example_id": "C_226_0*0de9d728e4dfb00d4864c75601af3f7e"
        },
        {
            "text": "at Russell Road and Hacienda Avenue and between Polaris Avenue and Dean Martin Drive, just west of Interstate 15",
            "start_logit": 0.4997936487197876,
            "end_logit": 2.2766637802124023,
            "retrieval_logit": 1.0886424779891968,
            "retriever_prob": 0.1666380763053894,
            "example_id": "C_226_0*1ff7a54749ba1f00e4ec80ddecd1edbd"
        },
        {
            "text": "2002\u201303",
            "start_logit": 10.987645149230957,
            "end_logit": 11.300861358642578,
            "retrieval_logit": 6.459817886352539,
            "retriever_prob": 0.16661007702350616,
            "example_id": "C_226_0*09325f19949f1f7142159a83911e7172"
        }
    ],
...
```

All retriever_prob are the same (0.166) and these same 6 passages are returned for every conversation. *It seems that the passage_reps are somehow not correct and there is something wrong in the retriever module.*

1. Could you please give me some insight into what is going wrong with the code? I didn't modify the codes at all (except for some minor stuff regarding img path error in order to make the code run, it was giving errors) and I followed the default and paper-mentioned parameters.
2. Could you please also provide the retriever best checkpoint and pipeline best checkpoint that you used in the paper? This will immensely help to reproduce the results.

Hoping to receive your answer!

**Comment by shihabrashid-ucr** [comment]
Update:
 figured out why recall is 1.0. Code was with `EG`.
changed it so that `include_positive_passage` is `False` still getting worse results in `test` set.
I think ndcg and recall are not 100 multiplied. But f1 and EM are.
```
{"f1": 0.20553723445049465, "human_f1": 93.24725462861055, "EM": 0.001694915254237288, 
"retriever_ndcg": 0.004393216594740101, "retriever_recall": 0.03898305084745763}
```

**Comment by liyongqi67** [comment]
I just updated the running steps. In case of any other queries, please do not hesitate to email me directly as I do not frequently check GitHub issues.

**Comment by liyongqi67** [comment]
> Update: figured out why recall is 1.0. Code was with `EG`. changed it so that `include_positive_passage` is `False` still getting worse results in `test` set. I think ndcg and recall are not 100 multiplied. But f1 and EM are.
> 
> ```
> {"f1": 0.20553723445049465, "human_f1": 93.24725462861055, "EM": 0.001694915254237288, 
> "retriever_ndcg": 0.004393216594740101, "retriever_recall": 0.03898305084745763}
> ```
Try the code now. Just load the released checkpoint and test it. The code will print the results
=======================
len(f1s) 590
len(human_f1) 590
Overall F1 3.584818194987687
Human F1 93.24725462861055
EM 0.0288135593220339
=======================
ndcg(@top_k_for_retriever) 0.07655641068040793
set_recall(@top_k_for_retriever) 0.4271186440677966
=======================
top_k_for_retriever=2000

**Comment by liyongqi67** [comment]
> Update: figured out why recall is 1.0. Code was with `EG`. changed it so that `include_positive_passage` is `False` still getting worse results in `test` set. I think ndcg and recall are not 100 multiplied. But f1 and EM are.
> 
> ```
> {"f1": 0.20553723445049465, "human_f1": 93.24725462861055, "EM": 0.001694915254237288, 
> "retriever_ndcg": 0.004393216594740101, "retriever_recall": 0.03898305084745763}
> ```

Tyr the release checkpoint now. It will print the results as
```
=======================
len(f1s) 590
len(human_f1) 590
Overall F1 3.584818194987687
Human F1 93.24725462861055
EM 0.0288135593220339
=======================
=======================
ndcg(@top_k_for_reader) nan
set_recall(@top_k_for_reader) nan
=======================
=======================
ndcg(@top_k_for_retriever) 0.07655641068040793
set_recall(@top_k_for_retriever) 0.4271186440677966
=======================
```
top_k_for_retriever is 2000 and top_k_for_reader is 10
