### ISSUE TITLE
Is it possible to provide the original (non-linearized) table data?

### ISSUE THREAD

**Issue by wu1hong** [liyongqi67/MMCoQA#7]
Hi, I am very interested in your work. I must say it is a good job.

I just wonder if it is possible to provide original table-form table data for other implementation of table encoder?

Best wishes!

**Comment by liyongqi67** [comment]
What does the original table-form table data mean? In the released dataset, the information about a table includes column names and cells.

**Comment by liyongqi67** [comment]
Reopen this issue if have other problems
